In [2]:
import numpy as np

# Function to train the Hebbian network
def train_hebbian(X, epochs, learning_rate):
    # Initialize weights and bias to zero
    n_samples, n_features = X.shape
    weights = np.zeros(n_features)

    # Training loop
    for epoch in range(epochs):
        for i in range(n_samples):
            for j in range(n_features):
                # Apply the Hebbian learning rule
                weights[j] += learning_rate * X[i, j] * X[i, j]

    return weights

# Function to make predictions using the trained Hebbian network
def predict_hebbian(X, weights):
    return np.dot(X, weights)


In [6]:
# Define input for AND operation
X_and = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])

# Add a bias 
X_and_bias = np.hstack([X_and, np.ones((X_and.shape[0], 1))])

# Training for AND operation
weights_and = train_hebbian(X_and_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_and = predict_hebbian(X_and_bias, weights_and)

weights_and, predictions_and

(array([20., 20., 40.]), array([40., 60., 60., 80.]))

In [12]:
# Define input for OR operation
X_or = np.array([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]])

# Add a bias 
X_or_bias = np.hstack([X_or, np.ones((X_or.shape[0], 1))])

# Train for OR operation
weights_or = train_hebbian(X_or_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_or = predict_hebbian(X_or_bias, weights_or)

weights_or, predictions_or

(array([20., 20., 40.]), array([40., 60., 60., 80.]))

In [13]:
# Define input for NOT operation (single input)
X_not = np.array([[0],
                  [1]])

# Add a bias
X_not_bias = np.hstack([X_not, np.ones((X_not.shape[0], 1))])

# Train for NOT operation
weights_not = train_hebbian(X_not_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_not = predict_hebbian(X_not_bias, weights_not)
weights_not, predictions_not

(array([10., 20.]), array([20., 30.]))

In [14]:
# Define input for NAND operation
X_nand = np.array([[0, 0],
                    [0, 1],
                    [1, 0],
                    [1, 1]])

# Add a bias term to the input
X_nand_bias = np.hstack([X_nand, np.ones((X_nand.shape[0], 1))])

# Train for NAND operation
weights_nand = train_hebbian(X_nand_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_nand = predict_hebbian(X_nand_bias, weights_nand)

weights_nand, predictions_nand

(array([20., 20., 40.]), array([40., 60., 60., 80.]))

In [15]:
X_nor = np.array([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]])

# Add a bias
X_nor_bias = np.hstack([X_nor, np.ones((X_nor.shape[0], 1))])

# Train for NOR operation
weights_nor = train_hebbian(X_nor_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_nor = predict_hebbian(X_nor_bias, weights_nor)

weights_nor, predictions_nor

(array([20., 20., 40.]), array([40., 60., 60., 80.]))

In [20]:
# Define input for ANDNOT operation (AND with the NOT of X2)
X_andnot = np.array([[0, 1],
                     [0, 0],
                     [1, 1],
                     [1, 0]])

# Add a bias
X_andnot_bias = np.hstack([X_andnot, np.ones((X_andnot.shape[0], 1))])

# Train for ANDNOT operation
weights_andnot = train_hebbian(X_andnot_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_andnot = predict_hebbian(X_andnot_bias, weights_andnot)

weights_andnot, predictions_andnot

(array([20., 20., 40.]), array([60., 40., 80., 60.]))

In [19]:
# Define input for XOR operation
X_xor = np.array([[0, 0],
                  [0, 1],
                  [1, 0],
                  [1, 1]])

# Add a bias
X_xor_bias = np.hstack([X_xor, np.ones((X_xor.shape[0], 1))])

# Train for XOR operation
weights_xor = train_hebbian(X_xor_bias, epochs=100, learning_rate=0.1)

# Make predictions
predictions_xor = predict_hebbian(X_xor_bias, weights_xor)

weights_xor, predictions_xor


(array([20., 20., 40.]), array([40., 60., 60., 80.]))